feat: Open Telemetry target
babbel/puma-plugin-telemetry pull request #30
Opened 2024-12-19 16:26 UTC by joshwestbrook

Add support for an Open Telemetry target as an alternative to DataDog.

Wasn't sure of the best way to make it so that consumers of this gem don't have to pull in both the `dogstatsd-ruby` and `opentelemetry-*` gems in order to use one of the targets. Open to any suggestions! 😄 

Note: The OTel Ruby Metrics SDK is under active development, so there is one pending PR and a pending release for gauge support:
-  https://github.com/open-telemetry/opentelemetry-ruby/pull/1780
- https://github.com/open-telemetry/opentelemetry-ruby/commit/bb5159598850b42e9da54608a8af2fbe422193b7

2025-01-10 14:20 UTC, driv3r requested changes
It can be simplified quite a bit regarding optional gems, as DD statsd was optional from the start anyway, plus you have to initialize the client manually - so there's no automatic setup for this, so we don't actually reference any 3rd party classes.

2025-01-10 14:20 UTC, driv3r commented
@joshwestbrook also sorry for such a long reply! Just came back from holidays

2025-01-13 15:41 UTC, joshwestbrook commented on README.md
> +**NOTE** Be sure to have `opentelemetry-metrics-sdk` gem installed.
Sure thing! https://github.com/babbel/puma-plugin-telemetry/pull/30/commits/b7aa0f06b71d6800e8915f6b7132f1f7ab7f949d

2025-01-13 15:41 UTC, joshwestbrook commented on lib/puma/plugin/telemetry/targets/datadog_statsd_target.rb
> +end
That makes it way simpler 😄 https://github.com/babbel/puma-plugin-telemetry/pull/30/commits/b7aa0f06b71d6800e8915f6b7132f1f7ab7f949d

2025-01-13 15:42 UTC, joshwestbrook commented
> @joshwestbrook also sorry for such a long reply! Just came back from holidays

No worries at all! Thanks for taking a look

2025-02-10 14:29 UTC, driv3r approved these changes

2025-12-04 18:56 UTC, stevenharman commented
As this repo seems… abandoned? I've forked and started adding things we need in production, including Puma 7 support. I'm currently [adding OTel support too](https://github.com/stevenharman/puma-plugin-telemetry_too/pull/3).

2026-08-05 12:53 UTC, amrrbakry commented on spec/puma/plugin/telemetry/config_spec.rb
> +
This double does not raise: RSpec doubles accept any arguments for stubbed messages unless constrained with `.with`, so `meter_provider.meter('puma.telemetry')` works fine against `double('otel meter provider', meter: ...)`. Verified locally — the spec passes as-is, so we are leaving it unchanged.

2026-08-05 13:18 UTC, amrrbakry approved these changes

2026-08-05 13:29 UTC, merged

2026-08-05 14:08 UTC, amrrbakry commented
Thank you so much! Released in https://github.com/babbel/puma-plugin-telemetry/releases/tag/v1.2.0